print("\t-----------------------------------------")
print("\t|\t MINIFY GADGETS\t\t\t|")
print("\t|\tPHONE STOCK UPDATE\t\t|")
print("\t|Phone type:\tIphones\t\t\t|")
print("\t|Phone model:\tiphone 14\t\t|")
print("\t|Brand:\t\tDYNAMIC ISLAND\t\t|")
print("\t|Release date:\tSEPTEMBER 15 2023\t|")
print("\t|Processor chip:A17 Bionic chip\t\t|")
print("\t-----------------------------------------")